import type { Project } from "@/lib/types/project";
import img from "@/public/hero.png";
import one from "@/assets/1.jpg";
import two from "@/assets/2.jpg";
import three from "@/assets/3.jpg";

export const projects: Project[] = [
  {
    slug: "los-lances-residence",
    title: "Los Lances Residence",
    location: "Tarifa, Spain",
    image: img,
    thumbnail: img,
    description:
      "A coastal residence with consistent sea views, steps from Los Lances Beach.",
    fullDescription:
      "Perched on the southern coast of Spain, the Los Lances Residence is a contemporary interpretation of Andalusian coastal architecture. The property features clean lines, locally-sourced stone, and floor-to-ceiling glazing that frames uninterrupted views of the Atlantic. Designed in collaboration with local architects, the home balances modern comfort with traditional craftsmanship, using lime-washed walls and terracotta roofing that blend seamlessly into the landscape.",
    price: "€890,000",
    beds: 4,
    baths: 3,
    area: "240 m²",
    status: "Available",
    completionDate: "2023",
    architect: "Mendoza & Partners",
    features: [
      "Private infinity pool with sea views",
      "Floor-to-ceiling glazing throughout",
      "Traditional Andalusian courtyard",
      "Solar panel installation",
      "Wine cellar with tasting room",
      "Double garage with EV charging",
    ],
    gallery: [img, one, two, three],
  },
  {
    slug: "capadocia-valley-house",
    title: "Capadocia Valley House",
    location: "Nevşehir, Turkey",
    image: img,
    thumbnail: img,
    description:
      "Set against ancient cave-dwelling landscapes, with private balloon-launch views.",
    fullDescription:
      "The Capadocia Valley House reimagines ancient stone-carved dwellings for contemporary living. Built into the natural rock formations of Cappadocia, the home preserves centuries-old architectural techniques while incorporating modern amenities. The property offers panoramic views of the surrounding fairy chimneys and valleys, with a private terrace that provides front-row seats to annual hot air balloon launches at sunrise.",
    price: "€420,000",
    beds: 3,
    baths: 2,
    area: "180 m²",
    status: "Available",
    completionDate: "2022",
    architect: "Stone & Sky Architecture",
    features: [
      "Cave-carved stone walls for natural insulation",
      "Private terrace with valley views",
      "Traditional Turkish hammam spa",
      "Hand-woven kilim details throughout",
      "Rooftop garden terrace",
    ],
    gallery: [img, one, two, three],
  },
  {
    slug: "saint-antoine-villa",
    title: "Saint Antoine Villa",
    location: "Provence, France",
    image: img,
    thumbnail: img,
    description:
      "A mountain-village villa surrounded by hiking trails and vineyard terraces.",
    fullDescription:
      "Saint Antoine Villa sits in the heart of Provence's Luberon region, nestled among lavender fields and ancient vineyards. Built in the style of a traditional Provençal bastide, the villa features a clay-tile roof, weathered limestone walls, and a central courtyard with a century-old olive tree. The property offers sweeping views of the surrounding mountains and vineyard terraces, with easy access to hiking and cycling trails.",
    price: "€1,250,000",
    beds: 5,
    baths: 4,
    area: "310 m²",
    status: "Coming Soon",
    completionDate: "2025",
    architect: "Atelier de Provence",
    features: [
      "Central courtyard with ancient olive tree",
      "Heated infinity pool overlooking vineyards",
      "Fully-equipped chef's kitchen with wine storage",
      "Guest house with separate entrance",
      "Olive grove and kitchen garden",
      "Home cinema with leather seating",
    ],
    gallery: [img, one, two, three],
  },
  {
    slug: "nagano-retreat",
    title: "Nagano Retreat",
    location: "Nagano, Japan",
    image: img,
    thumbnail: img,
    description:
      "Traditional timber architecture restored for modern living, framed by mountains.",
    fullDescription:
      "The Nagano Retreat is a meticulous restoration of a 150-year-old kominka (traditional Japanese farmhouse), blending heritage carpentry with contemporary comfort. Located in the Japanese Alps, the property uses traditional joinery techniques without nails, natural materials like bamboo and washi, and features a rotenburo (outdoor hot spring bath) that overlooks the surrounding cedar forest. The design respects the original structure while meeting modern seismic and energy efficiency standards.",
    price: "¥98,000,000",
    beds: 3,
    baths: 2,
    area: "165 m²",
    status: "Sold",
    completionDate: "2021",
    architect: "Sato Heritage Restorations",
    features: [
      "Traditional timber framing without nails",
      "Outdoor hot spring bath (rotenburo)",
      "Tatami guest room with futon bedding",
      "Engawa veranda overlooking the mountains",
      "Modern seismic retrofitting",
      "Solar-powered LED lighting throughout",
    ],
    gallery: [img, one, two, three],
  },
  {
    slug: "herenstraat-townhouse",
    title: "Herenstraat Townhouse",
    location: "Utrecht, Netherlands",
    image: img,
    thumbnail: img,
    description:
      "A meticulously restored 19th-century canal house in the heart of Utrecht's historic district.",
    fullDescription:
      "The Herenstraat Townhouse is a masterclass in heritage restoration. Originally built in 1892, the property retains its original architectural details — ornate cornices, stained glass windows, and a hand-carved oak staircase — while featuring a fully modernized interior with smart home technology, underfloor heating, and energy-efficient systems. The townhouse sits on a quiet canal street steps from the city center.",
    price: "€675,000",
    beds: 3,
    baths: 2,
    area: "195 m²",
    status: "Available",
    completionDate: "2024",
    architect: "van Dijk Heritage Architects",
    features: [
      "Original 1892 oak staircase and cornices",
      "Smart home system with zoned climate control",
      "Energy Label A++ renovation",
      "Private canal-side garden",
      "Wine cellar with climate control",
      "Rooftop terrace with city views",
    ],
    gallery: [img, one, two, three],
  },
  {
    slug: "castellan-estate",
    title: "Castellan Estate",
    location: "Tuscany, Italy",
    image: img,
    thumbnail: img,
    description:
      "A restored medieval estate surrounded by olive groves and vineyards in rural Tuscany.",
    fullDescription:
      "Set on 40 hectares of rolling Tuscan countryside, the Castellan Estate is a 12th-century fortress restored to its former glory. The property produces its own olive oil and wine from on-site olive groves and vineyards. The main villa features thick stone walls, terracotta floors, and a private chapel, while a separate agriturismo building offers guest accommodation. The estate has been meticulously restored using traditional materials and techniques.",
    price: "€3,200,000",
    beds: 6,
    baths: 5,
    area: "520 m²",
    status: "Available",
    completionDate: "2020",
    architect: "Palazzo Restorations",
    features: [
      "12th-century stone fortress with private chapel",
      "Operational olive oil and wine production",
      "12-hectare vineyard with tasting room",
      "Heated infinity pool with infinity views",
      "Separate 4-guest agriturismo building",
      "Equestrian facilities and riding trails",
    ],
    gallery: [img, one, two, three],
  },
];
